<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Portofolio Kreator',
                'slug' => 'portofolio-kreator',
                'category' => 'website',
                'tag' => 'Website',
                'description' => 'Ruang digital untuk memamerkan karya dengan lebih berkesan.',
                'preview_color' => 'green',
                'icon' => '✦',
                'preview_label' => 'PORTFOLIO',
                'preview_title' => 'Showcase yang bercerita.',
                'is_dark_preview' => false,
                'long_description' => 'Portofolio Kreator membantu kamu menampilkan karya dengan cara yang lebih berkesan dan personal.',
                'meta_pills' => ['Siap pakai', 'Responsive', 'Mudah dikustomisasi'],
                'features' => [
                    ['icon' => '✦', 'title' => 'Gallery showcase', 'description' => 'Tampilkan karya dalam grid yang rapi dan menarik.'],
                    ['icon' => '☼', 'title' => 'About section', 'description' => 'Ceritakan latar belakang dan keahlianmu.'],
                    ['icon' => '↗', 'title' => 'Contact form', 'description' => 'Form kontak yang langsung terhubung ke email.'],
                    ['icon' => '⌂', 'title' => 'Multi-page', 'description' => 'Struktur halaman yang bisa dikembangkan sesuai kebutuhan.'],
                    ['icon' => '✓', 'title' => 'SEO ready', 'description' => 'Optimasi dasar sudah disiapkan untuk mesin pencari.'],
                    ['icon' => '⌁', 'title' => 'Fast loading', 'description' => 'Dibuat ringan agar cepat dibuka di semua perangkat.'],
                ],
                'audiences' => [
                    ['icon' => '✎', 'title' => 'Desainer', 'description' => 'Untuk menampilkan portofolio visual dengan lebih menarik.', 'points' => ['Gallery visual', 'Layout fleksibel']],
                    ['icon' => '⌘', 'title' => 'Developer', 'description' => 'Untuk menunjukkan proyek teknis dengan detail.', 'points' => ['Code snippet', 'Link ke repo']],
                    ['icon' => '♧', 'title' => 'Fotografer', 'description' => 'Untuk memamerkan foto dalam kualitas terbaik.', 'points' => ['Image optimization', 'Full-screen view']],
                ],
                'tech_stack' => [
                    ['label' => 'Frontend', 'values' => ['HTML', 'CSS', 'Responsive']],
                    ['label' => 'Backend', 'values' => ['Laravel', 'Blade']],
                    ['label' => 'Database', 'values' => ['SQLite', 'MySQL']],
                    ['label' => 'Deployment', 'values' => ['Cloud hosting', 'SSL included']],
                ],
                'faq' => [
                    ['question' => 'Apakah produk bisa disesuaikan?', 'answer' => 'Bisa. Warna, logo, alur, dan fitur tambahan dapat dibicarakan sebagai paket custom.'],
                    ['question' => 'Apakah sudah termasuk hosting?', 'answer' => 'Hosting tersedia sebagai paket tambahan dengan biaya bulanan yang terjangkau.'],
                    ['question' => 'Apakah saya mendapat source code?', 'answer' => 'Ya, source code penuh disertakan dalam setiap pembelian.'],
                    ['question' => 'Berapa lama proses setup?', 'answer' => 'Produk siap digunakan dalam 1–3 hari kerja setelah data dan branding diterima.'],
                ],
                'price_display' => 'Rp 199.000',
                'price_note' => 'sekali bayar · contoh harga',
                'is_active' => true,
            ],
            [
                'name' => 'Daily Planner',
                'slug' => 'daily-planner',
                'category' => 'produktif',
                'tag' => 'Produktivitas',
                'description' => 'Atur prioritas, catat progres, dan sisakan ruang untuk bernapas.',
                'preview_color' => 'sky',
                'icon' => '☼',
                'preview_label' => 'PLANNER',
                'preview_title' => 'Hari yang lebih tertata.',
                'is_dark_preview' => false,
                'long_description' => 'Daily Planner membantu kamu melihat prioritas, menyusun tugas, dan merawat ritme kerja—tanpa membuat hari terasa seperti spreadsheet.',
                'meta_pills' => ['Siap pakai', 'Responsive', 'Bisa dikembangkan'],
                'features' => [
                    ['icon' => '☼', 'title' => 'Daily overview', 'description' => 'Ringkasan tugas dan progress yang membantu kamu tahu harus mulai dari mana.'],
                    ['icon' => '✓', 'title' => 'Task management', 'description' => 'Kelompokkan tugas berdasarkan prioritas, status, dan waktu pengerjaan.'],
                    ['icon' => '◷', 'title' => 'Calendar view', 'description' => 'Lihat minggu yang akan datang dan siapkan pekerjaan sebelum menumpuk.'],
                    ['icon' => '♧', 'title' => 'Habit tracker', 'description' => 'Rawat kebiasaan kecil dengan progress visual yang mudah dipahami.'],
                    ['icon' => '↗', 'title' => 'Export & share', 'description' => 'Simpan rangkuman atau bagikan rencana kerja saat perlu berkolaborasi.'],
                    ['icon' => '⌁', 'title' => 'Lightweight', 'description' => 'Cepat dibuka, nyaman digunakan di laptop maupun layar ponsel.'],
                ],
                'audiences' => [
                    ['icon' => '✎', 'title' => 'Freelancer', 'description' => 'Untuk mengelola beberapa klien tanpa kehilangan gambaran besar.', 'points' => ['Pisahkan tugas per proyek', 'Jaga tenggat tetap terlihat']],
                    ['icon' => '⌘', 'title' => 'Tim kecil', 'description' => 'Untuk menyamakan prioritas dan membuat progres lebih mudah dibaca.', 'points' => ['Bagikan rencana mingguan', 'Kurangi update berulang']],
                    ['icon' => '♧', 'title' => 'Individu produktif', 'description' => 'Untuk merancang hari yang realistis, bukan jadwal yang melelahkan.', 'points' => ['Bangun rutinitas sederhana', 'Lihat progres diri sendiri']],
                ],
                'tech_stack' => [
                    ['label' => 'Frontend', 'values' => ['React', 'Tailwind CSS', 'Responsive UI']],
                    ['label' => 'Backend', 'values' => ['Node.js', 'REST API']],
                    ['label' => 'Database', 'values' => ['PostgreSQL', 'Secure Auth']],
                    ['label' => 'Deployment', 'values' => ['Cloud hosting', 'SSL included']],
                ],
                'faq' => [
                    ['question' => 'Apakah produk bisa disesuaikan?', 'answer' => 'Bisa. Warna, logo, alur, dan fitur tambahan dapat dibicarakan sebagai paket custom.'],
                    ['question' => 'Apakah sudah termasuk hosting?', 'answer' => 'Jelaskan dengan tegas apakah hosting termasuk, berapa lama, dan biaya perpanjangannya.'],
                    ['question' => 'Apakah saya mendapat source code?', 'answer' => 'Tuliskan model lisensi dengan jelas: source code penuh, akses terbatas, atau layanan berlangganan.'],
                    ['question' => 'Berapa lama proses setup?', 'answer' => 'Contoh jawaban: produk siap digunakan dalam 1–3 hari kerja setelah data dan branding diterima.'],
                ],
                'price_display' => 'Rp 249.000',
                'price_note' => 'sekali bayar · contoh harga',
                'is_active' => true,
            ],
            [
                'name' => 'Invoice Sederhana',
                'slug' => 'invoice-sederhana',
                'category' => 'bisnis',
                'tag' => 'Bisnis',
                'description' => 'Buat invoice profesional dan kelola pembayaran dengan lebih mudah.',
                'preview_color' => 'sand',
                'icon' => '↗',
                'preview_label' => 'INVOICE',
                'preview_title' => 'Tagihan tanpa ribet.',
                'is_dark_preview' => false,
                'long_description' => 'Invoice Sederhana membantu kamu membuat tagihan profesional tanpa kerumitan aplikasi akuntansi yang berlebihan.',
                'meta_pills' => ['Siap pakai', 'Responsive', 'PDF export'],
                'features' => [
                    ['icon' => '↗', 'title' => 'Buat invoice', 'description' => 'Generate invoice profesional dalam hitungan menit.'],
                    ['icon' => '✓', 'title' => 'Tracking pembayaran', 'description' => 'Pantau status pembayaran dengan jelas.'],
                    ['icon' => '☼', 'title' => 'Template rapi', 'description' => 'Desain invoice yang bersih dan profesional.'],
                    ['icon' => '◷', 'title' => 'Riwayat lengkap', 'description' => 'Arsip semua transaksi tersimpan rapi.'],
                    ['icon' => '♧', 'title' => 'Multi klien', 'description' => 'Kelola banyak klien dalam satu dashboard.'],
                    ['icon' => '⌁', 'title' => 'Export PDF', 'description' => 'Download invoice dalam format PDF siap kirim.'],
                ],
                'audiences' => [
                    ['icon' => '✎', 'title' => 'Freelancer', 'description' => 'Untuk menagih klien dengan profesional.', 'points' => ['Invoice cepat', 'Tracking pembayaran']],
                    ['icon' => '⌘', 'title' => 'UMKM', 'description' => 'Untuk mengelola keuangan tanpa software akuntansi rumit.', 'points' => ['Sederhana', 'Langsung pakai']],
                    ['icon' => '♧', 'title' => 'Konsultan', 'description' => 'Untuk penagihan berbasis proyek atau jam.', 'points' => ['Hitung otomatis', 'Laporan bulanan']],
                ],
                'tech_stack' => [
                    ['label' => 'Frontend', 'values' => ['Laravel Blade', 'CSS', 'Responsive']],
                    ['label' => 'Backend', 'values' => ['Laravel', 'PDF Generator']],
                    ['label' => 'Database', 'values' => ['MySQL', 'Secure Auth']],
                    ['label' => 'Deployment', 'values' => ['Cloud hosting', 'SSL included']],
                ],
                'faq' => [
                    ['question' => 'Apakah produk bisa disesuaikan?', 'answer' => 'Bisa. Template invoice bisa disesuaikan dengan branding bisnis Anda.'],
                    ['question' => 'Apakah sudah termasuk hosting?', 'answer' => 'Tersedia paket dengan hosting atau self-hosted sesuai kebutuhan.'],
                    ['question' => 'Apakah bisa multi-user?', 'answer' => 'Ya, tersedia opsi multi-user untuk tim keuangan.'],
                    ['question' => 'Berapa lama proses setup?', 'answer' => 'Setup awal hanya membutuhkan 1 hari kerja.'],
                ],
                'price_display' => 'Rp 299.000',
                'price_note' => 'sekali bayar · contoh harga',
                'is_active' => true,
            ],
            [
                'name' => 'Mini Store',
                'slug' => 'mini-store',
                'category' => 'website',
                'tag' => 'Website',
                'description' => 'Etalase online ringkas untuk produk yang ingin ditemukan.',
                'preview_color' => 'purple',
                'icon' => '⌂',
                'preview_label' => 'STORE',
                'preview_title' => 'Toko kecil, jangkauan luas.',
                'is_dark_preview' => false,
                'long_description' => 'Mini Store adalah etalase online yang ringkas namun lengkap, cocok untuk produk fisik maupun digital.',
                'meta_pills' => ['Siap pakai', 'Responsive', 'Katalog produk'],
                'features' => [
                    ['icon' => '⌂', 'title' => 'Katalog produk', 'description' => 'Tampilkan produk dengan gambar, deskripsi, dan harga.'],
                    ['icon' => '↗', 'title' => 'WhatsApp order', 'description' => 'Tombol order langsung via WhatsApp.'],
                    ['icon' => '✓', 'title' => 'Kategori', 'description' => 'Kelompokkan produk agar mudah ditemukan.'],
                    ['icon' => '☼', 'title' => 'Search', 'description' => 'Pencarian produk yang cepat dan akurat.'],
                    ['icon' => '◷', 'title' => 'Produk unggulan', 'description' => 'Highlight produk best seller di halaman utama.'],
                    ['icon' => '♧', 'title' => 'Mobile friendly', 'description' => 'Tampilan optimal di semua ukuran layar.'],
                ],
                'audiences' => [
                    ['icon' => '✎', 'title' => 'Penjual online', 'description' => 'Untuk yang ingin punya toko sendiri tanpa marketplace.', 'points' => ['Branding sendiri', 'Tanpa komisi']],
                    ['icon' => '⌘', 'title' => 'Kreator digital', 'description' => 'Untuk menjual produk digital seperti ebook atau template.', 'points' => ['Download otomatis', 'Lisensi sederhana']],
                    ['icon' => '♧', 'title' => 'Toko lokal', 'description' => 'Untuk memperluas jangkauan toko fisik ke online.', 'points' => ['Katalog digital', 'Order via WhatsApp']],
                ],
                'tech_stack' => [
                    ['label' => 'Frontend', 'values' => ['Laravel Blade', 'CSS', 'Responsive']],
                    ['label' => 'Backend', 'values' => ['Laravel', 'Admin Panel']],
                    ['label' => 'Database', 'values' => ['MySQL', 'File Storage']],
                    ['label' => 'Deployment', 'values' => ['Cloud hosting', 'SSL included']],
                ],
                'faq' => [
                    ['question' => 'Apakah produk bisa disesuaikan?', 'answer' => 'Bisa. Layout dan warna bisa disesuaikan dengan identitas brand.'],
                    ['question' => 'Apakah sudah termasuk hosting?', 'answer' => 'Tersedia paket hosting bulanan atau tahunan.'],
                    ['question' => 'Apakah bisa integrasi payment gateway?', 'answer' => 'Ya, bisa ditambahkan sebagai fitur tambahan.'],
                    ['question' => 'Berapa lama proses setup?', 'answer' => 'Toko bisa online dalam 2–3 hari kerja.'],
                ],
                'price_display' => 'Rp 349.000',
                'price_note' => 'sekali bayar · contoh harga',
                'is_active' => true,
            ],
            [
                'name' => 'Habit Garden',
                'slug' => 'habit-garden',
                'category' => 'produktif',
                'tag' => 'Produktivitas',
                'description' => 'Rawat kebiasaan harian dengan visual yang membuatmu betah.',
                'preview_color' => 'orange',
                'icon' => '✓',
                'preview_label' => 'HABIT',
                'preview_title' => 'Kebiasaan baik, pelan-pelan.',
                'is_dark_preview' => false,
                'long_description' => 'Habit Garden menggunakan pendekatan visual yang menyenangkan untuk membantu kamu membangun kebiasaan positif.',
                'meta_pills' => ['Siap pakai', 'Responsive', 'Visual tracking'],
                'features' => [
                    ['icon' => '✓', 'title' => 'Habit tracker', 'description' => 'Pantau kebiasaan harian dengan checklist visual.'],
                    ['icon' => '☼', 'title' => 'Streak counter', 'description' => 'Lihat berapa hari berturut-turut kamu konsisten.'],
                    ['icon' => '◷', 'title' => 'Calendar heatmap', 'description' => 'Visualisasi progres bulanan seperti GitHub contribution.'],
                    ['icon' => '♧', 'title' => 'Reminder', 'description' => 'Pengingat otomatis untuk kebiasaan yang tidak boleh terlewat.'],
                    ['icon' => '↗', 'title' => 'Export progress', 'description' => 'Bagikan pencapaianmu atau simpan sebagai motivasi.'],
                    ['icon' => '⌁', 'title' => 'Lightweight', 'description' => 'Aplikasi ringan yang tidak membebani perangkat.'],
                ],
                'audiences' => [
                    ['icon' => '✎', 'title' => 'Pembelajar', 'description' => 'Untuk membangun kebiasaan belajar setiap hari.', 'points' => ['Streak tracking', 'Visual motivasi']],
                    ['icon' => '⌘', 'title' => 'Kesehatan', 'description' => 'Untuk menjaga rutinitas olahraga dan pola makan.', 'points' => ['Daily checklist', 'Progress mingguan']],
                    ['icon' => '♧', 'title' => 'Mindfulness', 'description' => 'Untuk membangun kebiasaan meditasi dan journaling.', 'points' => ['Reminder lembut', 'Refleksi harian']],
                ],
                'tech_stack' => [
                    ['label' => 'Frontend', 'values' => ['React', 'CSS', 'Responsive']],
                    ['label' => 'Backend', 'values' => ['Laravel', 'REST API']],
                    ['label' => 'Database', 'values' => ['MySQL', 'Secure Auth']],
                    ['label' => 'Deployment', 'values' => ['Cloud hosting', 'SSL included']],
                ],
                'faq' => [
                    ['question' => 'Apakah produk bisa disesuaikan?', 'answer' => 'Bisa. Tema visual dan jenis habit bisa dikustomisasi.'],
                    ['question' => 'Apakah data tersimpan aman?', 'answer' => 'Ya, semua data dienkripsi dan tersimpan di server yang aman.'],
                    ['question' => 'Apakah ada notifikasi?', 'answer' => 'Ya, tersedia notifikasi via email atau browser push notification.'],
                    ['question' => 'Berapa lama proses setup?', 'answer' => 'Akun bisa langsung digunakan setelah registrasi.'],
                ],
                'price_display' => 'Rp 199.000',
                'price_note' => 'sekali bayar · contoh harga',
                'is_active' => true,
            ],
            [
                'name' => 'Dashboard Ringkas',
                'slug' => 'dashboard-ringkas',
                'category' => 'bisnis',
                'tag' => 'Bisnis',
                'description' => 'Ubah angka yang ramai menjadi keputusan yang lebih jelas.',
                'preview_color' => 'dark',
                'icon' => '⌘',
                'preview_label' => 'DASHBOARD',
                'preview_title' => 'Data yang mudah dibaca.',
                'is_dark_preview' => true,
                'long_description' => 'Dashboard Ringkas menyajikan data bisnis dalam tampilan yang bersih sehingga kamu bisa fokus pada keputusan, bukan angka.',
                'meta_pills' => ['Siap pakai', 'Responsive', 'Real-time data'],
                'features' => [
                    ['icon' => '⌘', 'title' => 'Ringkasan metrik', 'description' => 'KPI utama ditampilkan di bagian atas dashboard.'],
                    ['icon' => '☼', 'title' => 'Grafik interaktif', 'description' => 'Visualisasi data yang bisa di-hover untuk detail.'],
                    ['icon' => '✓', 'title' => 'Filter data', 'description' => 'Saring data berdasarkan periode, kategori, atau status.'],
                    ['icon' => '◷', 'title' => 'Export laporan', 'description' => 'Download data dalam format CSV atau PDF.'],
                    ['icon' => '↗', 'title' => 'Multi-user', 'description' => 'Akses berbeda untuk admin, manager, dan viewer.'],
                    ['icon' => '♧', 'title' => 'Dark mode', 'description' => 'Tema gelap yang nyaman untuk penggunaan lama.'],
                ],
                'audiences' => [
                    ['icon' => '✎', 'title' => 'Startup', 'description' => 'Untuk memantau pertumbuhan bisnis di tahap awal.', 'points' => ['Metrik kunci', 'Visual sederhana']],
                    ['icon' => '⌘', 'title' => 'Manajer', 'description' => 'Untuk mengambil keputusan berdasarkan data.', 'points' => ['Real-time update', 'Filter fleksibel']],
                    ['icon' => '♧', 'title' => 'Tim operasional', 'description' => 'Untuk melacak progres harian dan mingguan.', 'points' => ['Daily summary', 'Task tracking']],
                ],
                'tech_stack' => [
                    ['label' => 'Frontend', 'values' => ['React', 'Chart.js', 'Tailwind CSS']],
                    ['label' => 'Backend', 'values' => ['Laravel', 'REST API']],
                    ['label' => 'Database', 'values' => ['MySQL', 'Redis Cache']],
                    ['label' => 'Deployment', 'values' => ['Cloud hosting', 'SSL included']],
                ],
                'faq' => [
                    ['question' => 'Apakah produk bisa disesuaikan?', 'answer' => 'Bisa. Metrik dan tampilan dashboard bisa disesuaikan dengan kebutuhan bisnis.'],
                    ['question' => 'Apakah data real-time?', 'answer' => 'Ya, dashboard bisa di-setup untuk update real-time atau berkala.'],
                    ['question' => 'Apakah bisa integrasi dengan tools lain?', 'answer' => 'Ya, tersedia API untuk integrasi dengan tools eksternal.'],
                    ['question' => 'Berapa lama proses setup?', 'answer' => 'Dashboard siap digunakan dalam 3–5 hari kerja.'],
                ],
                'price_display' => 'Rp 499.000',
                'price_note' => 'sekali bayar · contoh harga',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
